"""Settings for ux.erplora.com — public docs site for the @erplora/ux library.

Hotframe requires a working DB engine even when the project does not use any
models, so we point ``DATABASE_URL`` at a local SQLite file and leave every
auth / module hook empty. The project ships zero modules and zero apps that
require a user model — the boot sequence's optional steps (active-module
mounting) are wrapped in try/except inside ``hotframe.bootstrap`` and
silently no-op when no ``Module`` table exists.

The middleware stack is reduced to what an unauthenticated, public,
read-only docs site actually needs: timeouts, error pages, body limits,
correlation IDs, observability, rate limits, language detection, CSP, and
the safe session middleware. CSRF and the module middleware manager are
dropped because the site has no mutating endpoints and no modules.
"""

from __future__ import annotations

from pathlib import Path

from hotframe import HotframeSettings
from pydantic_settings import SettingsConfigDict


REPO_ROOT = Path(__file__).resolve().parent.parent


class Settings(HotframeSettings):
    """ux site settings — public, no DB content, no auth, no modules."""

    model_config = SettingsConfigDict(
        env_prefix="UX_SITE_",
        env_file=".env",
        env_file_encoding="utf-8",
        case_sensitive=False,
        extra="ignore",
    )

    APP_TITLE: str = "ERPlora UX"

    # Allow the CDN-hosted UX bundle and Datastar runtime through CSP so
    # the docs site keeps working even when CSP_ENFORCE is flipped on.
    CSP_ALLOWED_SOURCES: dict[str, list[str]] = {
        "script": ["https://cdn.jsdelivr.net"],
        "style": ["https://cdn.jsdelivr.net"],
        "connect": [],
        "img": ["https://cdn.jsdelivr.net"],
        "font": [],
    }

    # Local-only deployment; SECRET_KEY auto-generated by the parent class.
    DEPLOYMENT_MODE: str = "local"
    DEBUG: bool = True

    # Hotframe still initializes a DB engine. Keep it as a small SQLite file
    # next to the repo root; nothing reads or writes it during normal use.
    DATABASE_URL: str = f"sqlite+aiosqlite:///{REPO_ROOT / "site.db"}"

    # No modules.
    MODULES_DIR: Path = REPO_ROOT / "_unused_modules"

    # No auth model wired in — every view in this site is public.
    AUTH_USER_MODEL: str = ""

    # Static files served from the repo's existing ``dist/`` build so the
    # site picks up the latest compiled CSS without any extra wiring.
    STATIC_ROOT: Path = REPO_ROOT / "dist"
    STATIC_URL: str = "/static/"

    # Reduced middleware stack — the standard one assumes a user model and
    # CSRF-protected forms. The docs site has neither.
    MIDDLEWARE: list[str] = [
        "hotframe.middleware.timeout.TimeoutMiddleware",
        "hotframe.middleware.error_pages.ErrorPageMiddleware",
        "hotframe.middleware.body_limit.BodyLimitMiddleware",
        "asgi_correlation_id.CorrelationIdMiddleware",
        "hotframe.middleware.observability.RequestObservabilityMiddleware",
        "hotframe.middleware.rate_limit.APIRateLimitMiddleware",
        "hotframe.middleware.language.LanguageMiddleware",
        "hotframe.middleware.csp.CSPMiddleware",
        "hotframe.middleware.session_safe.RobustSessionMiddleware",
    ]


settings = Settings()
